services:
  db:
    image: postgres:15-alpine
    container_name: medichain-db
    restart: always
    environment:
      POSTGRES_USER: medichain_user
      POSTGRES_PASSWORD: medichain_password
      POSTGRES_DB: medichain_db
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: medichain-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://medichain_user:medichain_password@db:5432/medichain_db?schema=public
      PORT: 5000
    depends_on:
      - db

volumes:
  postgres_data:
